import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from "react";
import { Link } from "react-router-dom";
import { useEventStore } from "../store/useEventStore";
export default function Memories() {
    const events = useEventStore((s) => s.events);
    const past = useMemo(() => events.filter((m) => m.isPast || new Date(m.date) < new Date()), [events]);
    return (_jsxs("div", { className: "min-h-screen", children: [_jsx("h1", { className: "text-3xl font-bold text-gray-800 dark:text-gray-100 mb-2", children: "\uD83D\uDD70 Past Moments" }), _jsx("p", { className: "text-gray-600 dark:text-gray-400 mb-6", children: "These moments have already passed, but you can still edit details, add reflections, or update preparations." }), past.length === 0 ? (_jsx("p", { className: "text-gray-500", children: "No past moments yet." })) : (_jsx("div", { className: "grid gap-4 md:grid-cols-2 lg:grid-cols-3", children: past.map((e) => (_jsxs("div", { className: "relative rounded-2xl p-4 transition-all bg-white dark:bg-gray-800 border border-amber-200 dark:border-amber-700", children: [_jsx("span", { className: "absolute top-2 right-3 text-xs px-2 py-1 bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300 rounded-full", children: "\u23F3 Past Due" }), _jsx("h3", { className: "text-lg font-semibold text-gray-800 dark:text-gray-100 mb-1", children: e.name || e.title }), _jsx("p", { className: "text-sm text-gray-500", children: new Date(e.date).toLocaleDateString() }), e.description && _jsx("p", { className: "text-sm text-gray-600 dark:text-gray-300 mt-1", children: e.description }), _jsxs("div", { className: "mt-3 flex gap-2", children: [_jsx(Link, { to: `/event/${e.id}`, className: "inline-block px-3 py-1.5 rounded-md bg-blue-500 dark:bg-blue-600 text-white hover:bg-blue-600 dark:hover:bg-blue-700 transition text-sm", children: "Open" }), _jsx(Link, { to: `/edit/${e.id}`, className: "inline-block bg-blue-200 dark:bg-blue-700 hover:bg-blue-300 dark:hover:bg-blue-600 rounded px-2 py-1 text-sm transition text-gray-700 dark:text-gray-200", children: "Edit" })] })] }, e.id))) }))] }));
}
